name: Bunny
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: deps
        run: pip install requests

      - name: build
        env:
          GH_USER: ${{ github.actor }}
        run: |
          python scripts/bunny.py
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "actions-bot"
          git add bunny-runner.svg
          git commit -m "update bunny" || true
          git push
